src = ["app"]

exclude = [
    ".git",
    "third_party",
    "venv",
]

# Assume Python 3.9
target-version = "py39"

[lint]
select = [
  "I", # Enable isort rules.
]
ignore = []

[lint.isort]
force-single-line = true
