sudo: false
dist: trusty
language: python
python:
  - "2.7"
notifications:
  email: false
install:
    # Requirements needed for Travis CI
    - pip install coveralls
    - pip install -r dev_requirements.txt
    - pip install -r requirements.txt
script:
    ./build
after_success:
    coveralls
