version: 2.1
orbs:
  codecov: codecov/codecov@1.0.4
jobs:
  build:
    docker:
      - image: circleci/python:3.7.3
    steps:
      - checkout
      - run:
          name: Install requirements and run build script
          command: |
            mkdir -p ./venv
            virtualenv --python python3 ./venv
            . venv/bin/activate
            pip install pyyaml coveralls
            pip install --requirement requirements.txt
            pip install --requirement dev_requirements.txt
            ./build
      - codecov/upload:
          file: .coverage
workflows:
  test:
    jobs:
      - build
