version: 2.1
jobs:
  check_whitespace:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - run:
          name: Check for trailing whitespace
          command: ./dev-scripts/check-trailing-whitespace
      - run:
          name: Check that all text files end in a trailing newline
          command: ./dev-scripts/check-trailing-newline
  build_python:
    docker:
      - image: circleci/python:3.7.3
    steps:
      - checkout
      - run:
          name: Install requirements and run build script
          command: |
            mkdir -p ./venv
            virtualenv --python python3 ./venv
            . venv/bin/activate
            pip install --requirement requirements.txt
            pip install --requirement dev_requirements.txt
            ./dev-scripts/build-python
      - persist_to_workspace:
          root: ./
          paths:
            - .coverage
workflows:
  test:
    jobs:
      - check_whitespace
      - build_python
