version: 1
update_configs:
  - package_manager: "python"
    directory: "/"
    update_schedule: "weekly"
    ignored_updates:
      - match:
          # We need to use a specific pylint version that's compatible with
          # DocStringChecker.
          dependency_name: "pylint"
