#!/usr/bin/env bash

# Exit on first failure.
set -e

# Exit on unset variable.
set -u

# Echo commands before executing them, by default to stderr.
set -x

# Location of app source files.
readonly SOURCE_DIR=app

# Location of virtualenv.
readonly VIRTUALENV_DIR=venv

# Delete pyc files from previous builds.
find . \
  -name "*.pyc" \
  -type f \
  -not -path "./${VIRTUALENV_DIR}/*" \
  -delete

# Run unit tests and calculate code coverage.
coverage run \
  --source "${SOURCE_DIR}" \
  --omit "*_test.py" \
  -m unittest discover --pattern "*_test.py"
coverage report

# Check that source has correct formatting.
yapf --diff --recursive ./

# Run static analysis for Python bugs/cruft.
ruff check \
  "${SOURCE_DIR}/"

# Run static analysis for Python bugs/cruft.
pyflakes "${SOURCE_DIR}/"

# Check for other style violations.
PYTHONPATH="${SOURCE_DIR}" pylint "${SOURCE_DIR}"
